apiVersion: v1
kind: Service
metadata:
  name: djangoservice
  namespace: django-todo-app


spec:
  type: LoadBalancer
  selector:
    app: django-app

  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  
  
  
