apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None  # Headless service (no cluster IP)
  selector:
    app: mongo  # Matches the StatefulSet labels
  ports:
    - port: 27017
      targetPort: 27017
